### PR TITLE
Updated Roundcube

### PR DESCRIPTION
**Pull request by djhetherington**
Updated Roundcube for you guys

### CODE REVIEW

**Comment by nuxwin** [comment]
Why you updated requirements to PHP >=5.4.45 in composer.json file?
Upstream still say: "php": ">=5.3.7"

See https://github.com/roundcube/roundcubemail/blob/1.2.1/composer.json-dist

**Comment by djhetherington** [comment]
Went by this PHP requirements in this document https://github.com/roundcube/roundcubemail/wiki/Install-Requirements.

**Comment by nuxwin** [comment]
@djtye 

Waiting for an answer: https://github.com/roundcube/roundcubemail/issues/5438

If this is confirmed, we will have to drop support for Ubuntu Precise...

**Comment by nuxwin** [comment]
@djtye According answer from upstream authors, the 1.2.x Serie is working with PHP >= 5.3.7. Can you fix the composer.json file?

Thank you.

**Comment by djhetherington** [comment]
Completed the fix :)

**Pull request closed without merging**
