### PR TITLE
added auto responder plugin

### PR DESCRIPTION
**Pull request by MuhKuh7**
Added an autoresponder plugin. This is only the plugin, no config.

It also needs changes in the installer of course and a config.inc.php with the following settings:
$rcmail_config['autoresponder_driver'] = 'sql';
$rcmail_config['autoresponder_db_dsn'] = 'mysqli://roundcube_user:pass@localhost/ispcp';

### CODE REVIEW

**Comment by nuxwin** [comment]
Hello ;

Thanks you for your contribution. I'll integrate this ASAP

**Comment by MuhKuh7** [comment]
Will this go into 1.2.0?
If you want I can open a PR for the installer/config part in imscp. Perhaps we should also add an option in the installer so the admin can disable this feature if he doesn't want the users to have it? Or do we need more control over it?

**Comment by nuxwin** [comment]
I'm not sure we must integrate that plugin in our branch.

**Comment by MuhKuh7** [comment]
You think we should make it as a plugin and install it using the hook system?

**Comment by nuxwin** [comment]
We are already provide a responder feature in the panel, which is more efficient than the one you provide via roundcube. A responder feature provided by a roundcube plugin means necessarily some delay because roundcube is not a daemon.

To resume

i-MSCP responder:

incoming mail ---> postfix ---> transport (responder)

Roundcube responder:

incoming mail ---> wait for roundcube httpd request ---> send auto response

**Comment by MuhKuh7** [comment]
I don't understand. This plugin sets the autoresponder of imscp and triggers the daemon. It's just a way for a user to set the responder message. Why should this be less efficient?

**Comment by nuxwin** [comment]
Oh... it's just an interface to setup the i-MSCP autoresponder. Well ok forget my previous comments. Please, provide the installer part via a PR and I'll review/merge it in time.

Sorry for the misunderstanding there

**Comment by MuhKuh7** [comment]
Ah, just saw you edited your previous post, now I understand why you thought it would be less efficient :D It would be indeed :) I'll provide the install part asap.

**Comment by MuhKuh7** [comment]
Installer PR: https://github.com/i-MSCP/imscp/pull/32

**Comment by nuxwin** [comment]
Thx. I'll merge ASAP

**Comment by ghost** [comment]
hello,
Is the autoresponder plugin also for  webmail?
We use i-MSCP 1.1.14 and roundcube webmail 0.9.5 for our clients and we need an autoresponder for webmail.

**Comment by nuxwin** [comment]
@i-MSCP/plugin-managers 

Does should we provide such thing or should we close that PR?

**Comment by reneschuster** [comment]
@nuxwin 

With the [managesieve](https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/config.inc.php.dist#L83) plugin for Roundcube it is now also possible to create an autoresponder for out-of-office messages.I already integrated that for the latest RoundcubePlugins. https://github.com/i-MSCP/plugins/commit/a4fd190b3a87d3d62879719272b89f93e0e96c03

**Comment by nuxwin** [comment]
@reneschuster 

So we can close, right?

**Comment by reneschuster** [comment]
In my opinion, yes.

**Comment by nuxwin** [comment]
Ok ;) I close it ;)

**Pull request closed without merging**
